version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bibliobus_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliobus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bibliobus_backend
    restart: always
    environment:
      PORT: 3001
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/bibliobus?schema=public"
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./package*.json:/app/package*.json

    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
