import { Router } from "express";
import authRoutes from "./auth.routes.js";
import userRoutes from "./user.routes.js";
import bookRoutes from "./book.routes.js";
import reservationRoutes from "./reservation.routes.js";
import loanRoutes from "./loan.routes.js";
import busStopRoutes from "./busStop.routes.js";
import deliveryRoutes from "./delivery.routes.js";
import notificationRoutes from "./notification.routes.js";
import transactionRoutes from "./transaction.routes.js";
const router = Router();
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/books", bookRoutes);
router.use("/reservations", reservationRoutes);
router.use("/loans", loanRoutes);
router.use("/bus-stops", busStopRoutes);
router.use("/deliveries", deliveryRoutes);
router.use("/notifications", notificationRoutes);
router.use("/transactions", transactionRoutes);
export default router;
